### ISSUE TITLE
Forum Post?

### ISSUE THREAD

**Issue by BernhardBaumrock** [Sebiworld/Twack#1]
Hey Sebi,
this module looks interesting! I have some suggestions - don't you want to open a forum thread for discussion? :)
Thx for sharing!
Bernhard

**Comment by Sebiworld** [comment]
Hi Bernhard,
I'm on it! I wanted to complete the documentation first, but since it is now published in the ProcessWire newsletter I will do it as soon as possible.

I really look forward to hear, what you and others think of it!

**Comment by BernhardBaumrock** [comment]
Great, thx :)
